### ISSUE TITLE
Cannot assign global promise

### ISSUE THREAD

**Issue by stevehipwell** [louy/typed-mongoose#4]
As mPromise is now [deprecated](https://github.com/Automattic/mongoose/wiki/5.0-Deprecation-Warnings) (with warnings in the console) and doesn't supporting `catch`; I'm attempting to use the [global promise](http://mongoosejs.com/docs/promises.html) with the following code `mongoose.Promise = global.Promise;`. This is causing a type error, I also assume that there will also be additional work to enable the promise type to be correctly typed?

**Comment by louy** [comment]
We need to figure out a way around this in typescript. You can't just change the type of `mongoose.Promise`. 

I'll take a look when I have some time but if you have any suggestions please share them.

**Comment by stevehipwell** [comment]
If you remove all of the mPromise stuff from the type definition then `Promise` will mean whatever is currently defined, in my case the es6 promise from the typescript base definition file. Then all I've done is hacked the promise replacement `(<any>mongoose).Promise = global.Promise;`.

**Comment by louy** [comment]
So DT definitions use a global type `MongoosePromise` that you have to set manually before you import their definitions. This unfortunately isn't possible with non-global typings. I couldn't get it to work no matter what I tried.

We better not use the global `Promise` type because it might not be there and doesn't reflect the actual behaviour of mongoose. I've had this discussion with @blakeembrey [previously.](https://github.com/typings/registry/pull/400#issuecomment-217670838)

Another solution I could come up with is having a new typing called `mongoose/promise` That can be pointed at any promise library. What this means is that everytime you install mongoose you'll have to install `mongoose/promise` and point it at something. For example to use `mpromise` it would be something like this:

``` bash
typings install -S mongoose
typings install -S mpromise --name mongoose/promise
```

Thoughts?

**Comment by louy** [comment]
@simonxca you might be interested in this as well.

**Comment by blakeembrey** [comment]
Side note: The referenced docs are for 5.0, are you using 5.0? It looks like when the mongoose typings are updated, they should go ahead and use the global promise (starting at 5.0). Unfortunately, I don't think there's a behaviour in TypeScript that can replicate the "no promises" comment. 

As for workarounds, I can't think of anything better either. I'm guessing you tried using generics without any success? Actually, what about using `typeof mongoose.Promise` and `mongoose.Promise` types everywhere and then relying on module augmentation? Can the current module be augmented?

Edit: In 2.0, the global approach seems to actually work perfectly - though it could be by accident. Augmenting `mongoose` introducing `Promise` is only allowed with 2.0. Once introduced, all the code in the `mongoose` namespace would start using the local `Promise` instead of the `global.Promise`. Works weirdly well, but it feels like that style of introduction may be a bug in `tsc`.

**Comment by simon-xiong-ca** [comment]
@louy Right now DT uses a definition called mongoose-promise that provides mongoose 4's default mpromise definitions. These are optionally installed via typings, but users can choose not to install it and pick another library by setting `type MongoosePromise<T>`.

Going off @blakeembrey's idea, I believe mongoose 5 will use global Promise so I don't think it would be a problem to use return type `method(): Promise<T>` in the mongoose definitions in the future and get rid of the reference to mongoose-promise.

  Not sure if this will work in 2.0, but currently we are able to augment the DT definitions like this:

```
declare module 'mongoose' {
  type Promise<T> = Q.Promise<T>;
}
```

So if users really wanted to override the global Promise they could and it would only affect promises in the mongoose module. If they want to stick with global Promises it won't spit out an error like it currently does since the global Promise should be defined.
